<?php

/**
 * @file
 * Custom functions and hooks for Brookshire Brothers
 *
 */

/**
 * Implements hook_menu().
 */
function brookshirebrotherscustom_menu() {

  $items = array();

  $items['tester'] = array(
    'title' => 'Test Functions',
    'page callback' => 'brookshirebrotherscustom_tester',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access administration pages'),
  );

  $items['describe'] = array(
    'title' => 'Test Functions',
    'page callback' => 'brookshirebrotherscustom_describe',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access administration pages'),
  );

  return $items;
}



function brookshirebrotherscustom_tester() {

  require_once (SOAP_CLIENT_BASEDIR.'/SforceEnterpriseClient.php');
  require_once (SOAP_CLIENT_BASEDIR.'/SforcePartnerClient.php');
  require_once (SOAP_CLIENT_BASEDIR.'/SforceHeaderOptions.php');
  require_once (SOAP_CLIENT_BASEDIR.'/SforceBaseClient.php');

  try {
    $mySforceConnection = new SforcePartnerClient();
    $mySforceConnection->createConnection(SOAP_CLIENT_BASEDIR.'/partner.wsdl.xml');
    $mySforceConnection->login(SOAP_CLIENT_USER, SOAP_CLIENT_PASSWORD);
    // $query = "Select Id, Store_Number__c, BillingStreet, BillingCity, BillingState, BillingPostalCode, Has_Weekly_Ad__c, Allows_Rx_Transfer_and_Refills__c from Account Where Type = 'BB Store'";
    $query = "Select Id from Account Where Type = 'BB Store'";
    $response = $mySforceConnection->query($query);

    print_r($response);
    $ids = array();
    foreach ($response->records as $object) {
      $ids[] = $object->Id;
    }

    print_r($ids);

    exit;

    $fieldList = "Store_Number__c, BillingStreet, BillingCity, BillingState, BillingPostalCode, Has_Weekly_Ad__c, Allows_Rx_Transfer_and_Refills__c";
    $sObjectType = "Account";

    $response = $mySforceConnection->retrieve($fieldList, $sObjectType, $ids);
    print_r($response);


  } catch (Exception $e) {
    echo $mySforceConnection->getLastRequest();
    echo $e->faultstring;
  }
}

function brookshirebrotherscustom_describe() {

  require_once (SOAP_CLIENT_BASEDIR.'/SforceEnterpriseClient.php');
  require_once (SOAP_CLIENT_BASEDIR.'/SforceHeaderOptions.php');
  require_once (SOAP_CLIENT_BASEDIR.'/SforceBaseClient.php');

  try {
    $mySforceConnection = new SforceEnterpriseClient();
    $mySoapClient = $mySforceConnection->createConnection(SOAP_CLIENT_BASEDIR.'/enterprise.wsdl.xml');
    $mylogin = $mySforceConnection->login(SOAP_CLIENT_USER, SOAP_CLIENT_PASSWORD);
    $response = $mySforceConnection->describeSObject("Account");
    print_r($response);


  } catch (Exception $e) {
    echo $mySforceConnection->getLastRequest();
    echo $e->faultstring;
  }
}