<?php

/**
 * @file
 * Custom functions and hooks for Brookshire Brothers
 *
 */

/**
 * Implements hook_menu().
 */
function brookshirebrotherscustom_menu() {

  $items = array();

  $items['tester'] = array(
    'title' => 'Test Functions',
    'page callback' => 'brookshirebrotherscustom_tester',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );

  return $items;
}


function brookshirebrotherscustom_tester() {
  require_once (SOAP_CLIENT_BASEDIR.'/SforceEnterpriseClient.php');

  try {
    $mySforceConnection = new SforceEnterpriseClient();
    $mySoapClient = $mySforceConnection->createConnection(SOAP_CLIENT_BASEDIR.'/enterprise.wsdl.xml');
    $mylogin = $mySforceConnection->login(SOAP_CLIENT_USER, SOAP_CLIENT_PASSWORD);
    print_r($mySforceConnection->describeSObject('Account'));

  } catch (Exception $e) {
    echo $mySforceConnection->getLastRequest();
    echo $e->faultstring;
  }
}
